# Generated by Django 4.0.5 on 2022-06-08 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auto',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
