# Generated by Django 4.0.5 on 2022-06-08 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0004_alter_auto_options_auto_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auto',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='auto',
            name='photo',
            field=models.ImageField(upload_to='photo/%Y/%m/%d'),
        ),
    ]
