# Generated by Django 4.0.5 on 2022-06-09 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0009_alter_auto_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='auto',
            name='likes',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
