# Generated by Django 4.0.5 on 2022-06-09 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0010_auto_likes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auto',
            old_name='description',
            new_name='description_en',
        ),
        migrations.AddField(
            model_name='auto',
            name='description_ru',
            field=models.TextField(blank=True),
        ),
    ]
