# Generated by Django 4.0.5 on 2022-06-09 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0011_rename_description_auto_description_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auto',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
