# Generated by Django 4.0.5 on 2022-06-09 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0012_auto_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auto',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='auto',
            name='description_ru',
        ),
        migrations.RemoveField(
            model_name='auto',
            name='info',
        ),
    ]
